export const featuredBlogs = [
  {
    id: 1,
    title: "Social Media App",
    img: "assets/images/img-3.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 2,
    title: "Rampa UI Design",
    img: "https://cdn.dribbble.com/users/702789/screenshots/15054318/media/4ea5d492b7b07eebc9528ff960794879.png?compress=1&resize=1200x900",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 3,
    title: "E-commerce Web Design",
    img: "https://cdn.dribbble.com/users/1387827/screenshots/15466426/media/deb2dca6762cd3610321c98bfccb0b72.png?compress=1&resize=1200x900",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 4,
    title: "assets/images/img-4.jpg",
    img: "https://cdn.dribbble.com/users/4095861/screenshots/15467417/media/d6a15c416626f12b31fa5ca1db192572.png?compress=1&resize=1200x900",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 5,
    title: "Hero Web Design",
    img: "https://cdn.dribbble.com/users/5031392/screenshots/15467520/media/c36b3b15b25b1e190d081abdbbf947cf.png?compress=1&resize=1200x900",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 6,
    title: "Banking App",
    img: "https://cdn.dribbble.com/users/3307260/screenshots/15468444/media/447b4501f7a145b05e11c70199a9c417.jpg?compress=1&resize=1200x900",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 7,
    title: "Content Social Media App",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 8,
    title: "Content Rampa UI Design",
    img: "assets/images/img-2.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 9,
    title: "Content E-commerce Web Design",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 21st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 10,
    title: "Content Relax Mobile App",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 01st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 11,
    title: "Content Keser Web Design",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 27st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
  {
    id: 12,
    title: "Content Banking App",
    img: "assets/images/img-5.jpg",
    link: "https://github.com/corozco6489/thingslearned",
    site: "https://corozco6489.github.io/thingslearned/",
    by:"Admin",
    date:" 25st may, 2021",
    description: " Lorem ipsum dolor sit amet consectetur adipisicing elit Commodi, illum",
  },
];
